apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-ui
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-ui
  template:
    metadata:
      labels:
        app: ecommerce-ui
    spec:
      containers:
        - name: ecommerce-ui
          image: ecommerceservice-ecommerce-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: REACT_APP_PROFILE_API_HOST
              value: http://authentication:3003
            - name: REACT_APP_PRODUCT_API_HOST
              value: http://product-catalog:3001
            - name: REACT_APP_INVENTORY_API_HOST
              value: http://product-inventory:3002
            - name: REACT_APP_ORDER_API_HOST
              value: http://order-management:9090
            - name: REACT_APP_SHIPPING_API_HOST
              value: http://shipping-and-handling:8080
            - name: REACT_APP_CONTACT_API_HOST
              value: http://contact-support:8000
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-ui
  namespace: ecommerce
spec:
  type: NodePort
  selector:
    app: ecommerce-ui
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30080
