apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      containers:
        - name: order-management
          image: ecommerceservice-order-management:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          env:
            - name: PRODUCT_CATALOG_API_HOST
              value: http://product-catalog:3001
            - name: PRODUCT_INVENTORY_API_HOST
              value: http://product-inventory:3002
            - name: SHIPPING_HANDLING_API_HOST
              value: http://shipping-and-handling:8080
---
apiVersion: v1
kind: Service
metadata:
  name: order-management
  namespace: ecommerce
spec:
  selector:
    app: order-management
  ports:
    - port: 9090
      targetPort: 9090
