apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-inventory
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-inventory
  template:
    metadata:
      labels:
        app: product-inventory
    spec:
      containers:
        - name: product-inventory
          image: ecommerceservice-product-inventory:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: product-inventory
  namespace: ecommerce
spec:
  selector:
    app: product-inventory
  ports:
    - port: 3002
      targetPort: 3002
